<div class="card">
    <div class="card-header">
        <h3 class="card-title">Edit User</h3>
    </div>
    <div class="card-body">
        <p>
            <a class="btn btn-success btn-sm" href="<?= $this->url('bpl-admin/user-management') ?>">
                Go to User Management
            </a>
        </p>

        <p>
            <strong>
                User : <?= $this->user->getEmail() . '(' . $this->user->getId() . ')' ?>
            </strong>
        </p>

        <?= $this->partial('bpl-admin/form', ['form' => $this->form]) ?>
        <?= $this->edited == true ? '<p>User edited successfully !</p>' : '' ?>
    </div>
</div>
