<div class="card">
    <div class="card-header">
        <h3 class="card-title">Add New User</h3>
    </div>
    <div class="card-body">
        <p>
            <a class="btn btn-success btn-sm" href="<?= $this->url('bpl-admin/user-management') ?>">
                Go to User Management
            </a>
        </p>

        <?= $this->partial('bpl-admin/form', ['form' => $this->form]) ?>
        <?= $this->created == true ? '<p>User created successfully !</p>' . $this->message : '' ?>
    </div>
</div>
