<?php

$form = $this->changePasswordForm;
$form->prepare();
$form->setAttribute('action', $this->url('bpl-user/change-password'));
$form->setAttribute('method', 'post');
$form->setAttribute('autocomplete', 'off');
?>
<div class="card">
    <div class="card-header">
        <h3 class="card-title"><?= $this->translate('Change Password') ?></h3>
    </div>
    <div class="card-body">
        <?= $this->partial('bpl-user/generic-form', ['form' => $form]) ?>
    </div>
</div>