<style>
    body {
        background: url('<?= $this->basePath() . '/img/Annapurna-massif-village-Nepal.jpg' ?>') no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }
    .logo-nta{
        display: block;
        margin-top : 1em;
        margin-bottom : .0em;
        margin-left: auto;
        margin-right: auto;
        width: 10%;
    }
    .banner-text {
        font-family: "Times New Roman", Times, serif;
    }
</style>
<div class="login-box">
    <div class="card card-outline card-secondary">
        <div class="card-header text-center">
            <img class="img-fluid" src="<?= $this->basePath() . '/img/nta-new-logo-01.png' ?>">
        </div>
        <div class="card-body">
            <div class="text-center">
                <a href="#" class="h6">Mobile Devices Management System</a>
            </div>
            <p></p>
            
            <?php if ($this->sent == true) { ?>

                <p><?php echo sprintf($this->translate('A reminder has been sent to your e-mail address %s. Follow instructions in the email to reset your password.'), $this->escapeHtml($this->email)); ?></p>

                <a href="<?php echo $this->url('bpl-user/login') ?>"><?php echo $this->translate('Back to login?'); ?></a>
            <?php } else { ?>
                <p>
                    Please enter your email address to receive password reset token.
                </p>
                <?php
                $form = $this->forgotPasswordForm;
                $form->prepare();
                $form->setAttribute('action', $this->url('bpl-user/forgot-password'));
                $form->setAttribute('method', 'post');
                $form->setAttribute('autocomplete', 'off');
                ?>

                <?= $this->partial('bpl-user/generic-form', ['form' => $form]) ?>

                <a href="<?php echo $this->url('bpl-user/login') ?>"><?php echo $this->translate('Back to login.'); ?></a>
                <?php
            }
            ?>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $(".navbar, footer").hide();
        $("body").addClass("login-page");
        $(".content-wrapper").css({'background': 'rgba(0, 0, 0, .0)'});
    });
</script>