<style>
    body {
        background: url('<?= $this->basePath() . '/img/Annapurna-massif-village-Nepal.jpg' ?>') no-repeat center center fixed;
        -webkit-background-size: cover;
        -moz-background-size: cover;
        -o-background-size: cover;
        background-size: cover;
    }
    .logo-nta{
        display: block;
        margin-top : 1em;
        margin-bottom : .0em;
        margin-left: auto;
        margin-right: auto;
        width: 10%;
    }
    .banner-text {
        font-family: "Times New Roman", Times, serif;
    }
</style>
<div class="login-box">
    <div class="card card-outline card-secondary">
        <div class="card-header text-center">
            <img class="img-fluid" src="<?= $this->basePath() . '/img/nta-new-logo-01.png' ?>">
        </div>
        <div class="card-body">
            <div class="text-center">
                <a href="#" class="h6">Mobile Devices Management System</a>
            </div>
            <p></p>
            
            <?php if ($this->changed == true) {
                ?>
                <h5><?= $this->translate('Your password has been changed.') ?></h1>

                <p><?= $this->translate('You can now login using your new password.') ?></p>

                <a href="<?= $this->url('bpl-user/login') ?>"><?php echo $this->translate('Back to login.') ?></a>
            <?php } else { ?>
                <div class="text-center">
                    <h4><?= $this->translate('Reset Password') ?></h4>
                    <small>for <?= $resetRecord->getUser()->getEmail() ?></small>
                    <p></p>
                </div>
                
                <?php
                $form = $this->resetPasswordForm;
                $form->prepare();
                $form->setAttribute('action', $this->url('bpl-user/reset-password', [
                            'userId' => $resetRecord->getUser()->getId(), 'token' => $resetRecord->getRequestKey()
                ]));
                $form->setAttribute('method', 'post');
                $form->setAttribute('autocomplete', 'off');
                ?>

                <?= $this->partial('bpl-user/generic-form', ['form' => $form]) ?>

                <a href="<?php echo $this->url('bpl-user/login') ?>"><?php echo $this->translate('Back to login'); ?></a>
            <?php } ?>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $(".navbar, footer").hide();
        $("body").addClass("login-page");
        $(".content-wrapper").css({'background': 'rgba(0, 0, 0, .0)'});
    });
</script>