<div class="card">
    <div class="card-header">
        <h3 class="card-title">Delete confirmation</h3>
    </div>
    <div class="card-body">
        <p>
            <a class="btn btn-success btn-sm" href="<?= $this->url('bpl-admin/role-management') ?>">
                Cancel Deletion
            </a>
        </p>
        <p>
            Role Name : <?= $this->role->getName() ?>
        </p>
        <form action="<?= $this->url('bpl-admin/role-management', ['action' => 'delete', 'id' => $this->role->getId()]) ?>" method="POST">
            <button type="submit" class="btn btn-danger">
                Delete
            </button>
        </form>
    </div>
</div>
