<?php
use LaminasAdminLTE\ThemeOptions\PartialOption;
/* @var $page \Laminas\Navigation\Page\AbstractPage */
$page = $this->page;
$maxDepth = $this->maxDepth;
$class = $this->class;
$linkClass = '';
$labelClean = str_replace(' ', '_', $page->getLabel());
$icon = $page->showIcon == true ? $page->icon : false;
$childPagesCheck = $page->getPages();
foreach ($childPagesCheck as $cPage) {
    if($cPage->isActive()){
        $class .= ' menu-open active';
        $linkClass = 'active';
    }
}
?>
<li class="<?= $class ?>">
    <a href="#" class="nav-link <?= $linkClass ?>">
        <?= $icon!== false ? '<i class="nav-icon '. $icon .'"></i>' : '' ?>
        <p><?= $page->getLabel() ?></p>
    </a>
    <ul class="nav nav-treeview">
        <?php
        $childPages = $page->getPages();
        foreach ($childPages as $cPage) {
            $iconCpage = $cPage->showIcon == true ? $cPage->icon : false;
            if ($cPage->hasPages() && --$maxDepth > 0) {
                echo $this->partial(PartialOption::menuItemTree, [
                    'page' => $cPage,
                    'maxDepth' => $maxDepth,
                    'class' => 'dropdown-submenu dropdown-hover'
                ]);
            } else {
                echo $this->partial(PartialOption::menuItemSide, [
                    'page' => $cPage,
                ]);
            }
        }
        ?>
    </ul>
</li>
