<?php
/* @var $container Laminas\Navigation\Navigation */

use LaminasAdminLTE\ThemeOptions\PartialOption;

$container = $this->container;

$maxDepth = $this->navigation($container)->menu()->getMaxDepth();
?>
<ul class="<?= $this->navigation($container)->menu()->getUlClass(); ?>" data-widget="treeview" role="menu" data-accordion="false">
    <?php
    foreach ($container as $page) {
        if (!$this->navigation()->accept($page)) {
            continue;
        }
        $isActive = $page->isActive();
        $hasChildren = $page->hasPages();
        if ($hasChildren) {
            echo $this->partial(PartialOption::menuItemTree, [
                'page' => $page,
                'maxDepth' => $maxDepth,
                'class' => 'nav-item dropdown'
            ]);
        } else {
            echo $this->partial(PartialOption::menuItem, [
                'page' => $page,
                'class' => 'nav-link'
            ]);
        }
    }
    ?>
</ul>