<div class="card">
    <div class="card-header">
        <h3 class="card-title">Assign Roles to User</h3>
    </div>
    <div class="card-body">

        <p>
            <a class="btn btn-success btn-sm" href="<?= $this->url('bpl-admin/user-management') ?>">
                Go to User Management
            </a>
        </p>
        <p>
            <strong>
                User : <?= $this->user->getEmail() . '(' . $this->user->getId() . ')' ?>
            </strong>
        </p>
        <?= $this->partial('bpl-admin/form', ['form' => $this->form]) ?>
        <?= $this->created == true ? '<p>User Role Updated !</p>' . $this->message : '' ?>
    </div>
</div>
