<?php
/**
 * @author Bishwo Prasad Lamichhane <bishwo.prasad@gmail.com>
 */

use LaminasAdminLTE\ThemeOptions\PartialOption;

if($this->pageTitle == NULL){
    $pageTitle = $this->getAsset('brandnamefull');
}
?>
<!DOCTYPE html>
<html>
    <head>
        <?= $this->headMeta() ?>
        <?= $this->headTitle($pageTitle)->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
    </head>
    <body class="hold-transition sidebar-mini layout-boxed <?= $this->getAsset('accentColor') ?>">
        <div class="wrapper">
            <nav class="main-header navbar navbar-expand <?= $this->getAsset('topnavbarskin') ?>">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                    </li>
                </ul>
                <?=
                        $this->navigation('navigation')
                        ->menu($this->getAsset('topNavigationKey'))
                        ->setMinDepth(0)
                        ->setMaxDepth(3)
                        ->setUlClass('navbar-nav')
                        ->setPartial(PartialOption::$menuTop)
                ?>
                <?= $this->getAsset('showsearch') ? $this->partial(PartialOption::$searchForm) : '' ?>
                <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
                    <?= $this->getAsset('showcontrol') ? $this->partial(PartialOption::$customizPanel) : '' ?>
                </ul>
            </nav>
            <aside class="main-sidebar sidebar-dark-primary elevation-4">
                <a href="<?= $this->url('home') ?>" class="brand-link <?= $this->getAsset('brandLinkColor') ?>">
                    <img src="<?= $this->basePath($this->getAsset('brandLogo')) ?>" 
                         title="<?= $this->getAsset('brandnamefull') ?>" 
                         alt="<?= $this->getAsset('brandnamefull') ?>" 
                         class="brand-image img-circle elevation-3"
                         style="opacity: .8">
                    <span class="brand-text font-weight-light">
                        <?= $this->getAsset('brandnameshort') ?>
                    </span>
                </a>
                <div class="sidebar">
                    <?= $this->partial(\LaminasAdminLTE\ThemeOptions\PartialOption::$userInfoSidebar) ?>
                    <nav class="mt-2">
                        <?=
                                $this->navigation('navigation')
                                ->menu($this->getAsset('topNavigationKey'))
                                ->setMinDepth(0)
                                ->setMaxDepth(3)
                                ->setUlClass('nav nav-pills nav-sidebar flex-column')
                                ->setPartial(PartialOption::$menuSide)
                        ?>
                    </nav>
                </div>
            </aside>
            <div class="content-wrapper">
                <?php if($this->getAsset('showbreadcrumb')):  ?>
                    <section class="content-header">
                        <div class="container">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h4 class="m-0" id="pageTitleId">
                                        <?= $this->pageTitle ?>
                                    </h4>
                                </div>
                                <div class="col-sm-6">
                                    <?=
                                    $this->navigation('navigation')
                                        ->breadcrumbs($this->getAsset('navigationKeyForBreadcrumb'))
                                        ->setMinDepth(0)
                                        ->setSeparator('>') 
                                        ->setPartial(PartialOption::$breadcrumb)
                                    ?>
                                </div>
                            </div>
                        </div>
                    </section>
                <?php endif; ?>
                <section class="content">
                    <div class="container-fluid">
                        <?= $this->content ?>
                    </div>
                </section>
                <br/>
            </div>
            <?= $this->partial(PartialOption::$footer) ?>
            <?= $this->getAsset('showcontrol') ? '<aside class="control-sidebar control-sidebar-dark"></aside>' : '' ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>

