<?php
/**
 * @author Bishwo Prasad Lamichhane <bishwo.prasad@gmail.com>
 */
$title = $this->showAssets('brandnamefull', $this);
?>
<!DOCTYPE html>
<html>
    <head>
        <?= $this->showAssets('meta', $this) ?>
        <?= $this->headTitle($title)->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->showAssets('favicon', $this) ?>
        <?= $this->showAssets('css', $this) ?>
    </head>
    <body class="hold-transition sidebar-mini layout-fixed">
        <div class="wrapper">
            <nav class="main-header navbar navbar-expand navbar-white navbar-light">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                    </li>
                </ul>
                <?=
                        $this->navigation('navigation')
                        ->menu($this->showAssets('topNavigationKey', $this))
                        ->setMinDepth(0)
                        ->setMaxDepth(3)
                        ->setUlClass('navbar-nav')
                        ->setPartial('partial/menu-top')
                ?>
                <?= $this->showAssets('showsearch', $this) ? $this->partial('partial/search-form') : '' ?>
                <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
                    <?= $this->showAssets('showcontrol', $this) ? $this->partial('partial/customize-panel') : '' ?>
                </ul>
            </nav>
            <aside class="main-sidebar sidebar-dark-primary elevation-4">
                <a href="<?= $this->url('home') ?>" class="brand-link">
                    <img src="<?= $this->showAssets('brandLogo', $this) ?>" 
                         title="<?= $this->showAssets('brandnamefull', $this) ?>" 
                         alt="<?= $this->showAssets('brandnamefull', $this) ?>" 
                         class="brand-image img-circle elevation-3"
                         style="opacity: .8">
                    <span class="brand-text font-weight-light">
                        <?= $this->showAssets('brandnameshort', $this) ?>
                    </span>
                </a>
                <div class="sidebar">
                    <?= $this->partial(\LaminasAdminLTE\ThemeOptions\PartialOption::$userInfoSidebar, [
                        'userImage' => '../../dist/img/user2-160x160.jpg',
                        'userInfo'  => '<a href="#" class="d-block">Alexander Pierce</a>'
                    ]) ?>
                    <nav class="mt-2">
                        <?=
                                $this->navigation('navigation')
                                ->menu($this->showAssets('topNavigationKey', $this))
                                ->setMinDepth(0)
                                ->setMaxDepth(3)
                                ->setUlClass('nav nav-pills nav-sidebar flex-column')
                                ->setPartial('partial/menu-side')
                        ?>
                    </nav>
                </div>
            </aside>

            <!-- Content Wrapper. Contains page content -->
            <div class="content-wrapper">
                <?php if($this->showAssets('showbreadcrumb', $this)):  ?>
                    <section class="content-header">
                        <div class="container">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h4 class="m-0" id="pageTitleId">
                                        <?= $this->pageTitle ?>
                                    </h4>
                                </div>
                                <div class="col-sm-6">
                                    <?=
                                    $this->navigation('navigation')
                                        ->breadcrumbs()
                                        ->setMinDepth(0)
                                        ->setSeparator('>') 
                                        ->setPartial('partial/breadcrumb')
                                    ?>
                                </div>
                            </div>
                        </div>
                    </section>
                <?php endif; ?>

                <section class="content">
                    <div class="container-fluid">
                        <?= $this->content ?>
                        <br>
                    </div>
                </section>
            </div>
            <?= $this->partial('partial/footer') ?>
            <?= $this->showAssets('showcontrol', $this) ? '<aside class="control-sidebar control-sidebar-dark"></aside>' : '' ?>
        </div>
        <?= $this->showAssets('js', $this) ?>
    </body>
</html>

