<?php

use LaminasAdminLTE\ThemeOptions\PartialOption;

if ($this->pageTitle == NULL) {
    $pageTitle = $this->getConfig('logo');
}
$title = $this->getConfig('title_prefix') . $pageTitle . $this->getConfig('title_postfix');
?>
<!DOCTYPE html>
<html>
    <head>
        <?= $this->headMeta() . "\n" ?>
        <?= $this->headTitle($title)->setSeparator(' - ')->setAutoEscape(false) . "\n" ?>
        <?= $this->headLink() . "\n" ?>
        <?= $this->headScript() . "\n" ?>
    </head>
    <body class="hold-transition sidebar-collapse layout-top-nav <?= $this->getCssClass('body') ?>">
        <div class="wrapper">
            <?= $this->partial(PartialOption::$topNavigation, [
                    'showTopNavigation' => true,
                    'showTopBrand' => true,
                    'wrapInContainer' => true
                ]) 
            ?>
            <?php if ($this->getConfig('right_sidebar')) : ?>
                <aside class="control-sidebar control-sidebar-<?= $this->getConfig('right_sidebar_theme') ?>"></aside>
            <?php endif; ?>
            <div class="content-wrapper <?= $this->getCssClass("content_wrapper") ?>">
                <div class="content <?= $this->getCssClass("content") ?>">
                    <div class="content-header <?= $this->getCssClass("content_header") ?>">
                        <?php if ($this->getConfig('showBreadcrumb')): ?>
                            <div class="container">
                                <div class="row mb-2">
                                    <div class="col-sm-6">
                                        <h4 class="m-0" id="pageTitleId">
                                            <?= $this->pageTitle ?>
                                        </h4>
                                    </div>
                                    <div class="col-sm-6">
                                        <?=
                                                $this->navigation('navigation')
                                                ->breadcrumbs($this->getConfig('navigationKeyForBreadcrumb'))
                                                ->setMinDepth(0)
                                                ->setSeparator('/')
                                                ->setPartial(PartialOption::$breadcrumb)
                                        ?>
                                    </div>
                                </div>
                            </div>
                        <?php endif; ?>
                    </div>
                    <div class="container <?= $this->getCssClass("content") ?>">
                        <?= $this->content ?>
                    </div>
                </div>
                <br/>
            </div>
            <div class="container">
                <div class="content">
                    <?= $this->partial(PartialOption::$footer) ?>
                </div>
            </div>
        </div>
        <?= $this->inlineScript() . "\n" ?>
    </body>
</html>

