<?php
/**
 * @author Bishwo Prasad Lamichhane <bishwo.prasad@gmail.com>
 */
$title = $this->showAssets('brandnamefull', $this);
?>
<!DOCTYPE html>
<html>
    <head>
        <?= $this->showAssets('meta', $this) ?>
        <?= $this->headTitle($title)->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->showAssets('favicon', $this) ?>
        <?= $this->showAssets('css', $this) ?>
    </head>
    <body class="hold-transition sidebar-collapse layout-top-nav">
        <div class="wrapper">
            <nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
                <div class="container">
                    <a href="<?= $this->url('home') ?>" class="navbar-brand">
                        <img src="<?= $this->showAssets('brandLogo', $this) ?>" title="<?= $this->showAssets('brandnamefull', $this) ?>" alt="<?= $this->showAssets('brandnamefull', $this) ?>" class="brand-image img-circle elevation-3"
                             style="opacity: .8">
                        <span class="brand-text font-weight-light"><?= $this->showAssets('brandnameshort', $this) ?></span>
                    </a>
                    <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                        </li>
                    </ul>
                    <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse order-3" id="navbarCollapse">
                        <?=
                                $this->navigation('navigation')
                                ->menu($this->showAssets('topNavigationKey', $this))
                                ->setMinDepth(0)
                                ->setMaxDepth(3)
                                ->setUlClass('navbar-nav')
                                ->setPartial('partial/menu-top')
                        ?>
                        <?= $this->showAssets('showsearch', $this) ? $this->partial('partial/search-form') : '' ?>
                        <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
                            <?= $this->showAssets('showcontrol', $this) ? $this->partial('partial/customize-panel') : '' ?>
                        </ul>
                    </div>
                </div>
            </nav>
            <aside class="main-sidebar sidebar-dark-primary elevation-4">
                <a href="<?= $this->url('home') ?>" class="brand-link">
                    <img src="<?= $this->showAssets('brandLogo', $this) ?>" 
                         title="<?= $this->showAssets('brandnamefull', $this) ?>" 
                         alt="<?= $this->showAssets('brandnamefull', $this) ?>" 
                         class="brand-image img-circle elevation-3"
                         style="opacity: .8">
                    <span class="brand-text font-weight-light">
                        <?= $this->showAssets('brandnameshort', $this) ?>
                    </span>
                </a>
                <div class="sidebar">
                    <?= $this->partial(\LaminasAdminLTE\ThemeOptions\PartialOption::$userInfoSidebar, [
                        'userImage' => '../../dist/img/user2-160x160.jpg',
                        'userInfo'  => '<a href="#" class="d-block">Alexander Pierce</a>'
                    ]) ?>
                    <nav class="mt-2">
                        <?=
                                $this->navigation('navigation')
                                ->menu($this->showAssets('topNavigationKey', $this))
                                ->setMinDepth(0)
                                ->setMaxDepth(3)
                                ->setUlClass('nav nav-pills nav-sidebar flex-column')
                                ->setPartial('partial/menu-side')
                        ?>
                    </nav>
                </div>
            </aside>
            <div class="content-wrapper">
                <?php if($this->showAssets('showbreadcrumb', $this)):  ?>
                    <div class="content-header">
                        <div class="container">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h4 class="m-0" id="pageTitleId">
                                        <?= $this->pageTitle ?>
                                    </h4>
                                </div>
                                <div class="col-sm-6">
                                    <?=
                                    $this->navigation('navigation')
                                        ->breadcrumbs()
                                        ->setMinDepth(0)
                                        ->setSeparator('>') 
                                        ->setPartial('partial/breadcrumb')
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="content">
                    <div class="container">
                        <?= $this->content ?>
                    </div>
                </div>
            </div>
            <?= $this->showAssets('showcontrol', $this) ? '<aside class="control-sidebar control-sidebar-dark"></aside>' : '' ?>
            <?= $this->partial('partial/footer') ?>
        </div>
        <?= $this->showAssets('js', $this) ?>
    </body>
</html>

