<?php
/**
 * @author Bishwo Prasad Lamichhane <bishwo.prasad@gmail.com>
 */

use LaminasAdminLTE\ThemeOptions\PartialOption;

if($this->pageTitle == NULL){
    $pageTitle = $this->getAsset('brandnamefull');
}
?>
<!DOCTYPE html>
<html>
    <head>
        <?= $this->headMeta() ?>
        <?= $this->headTitle($pageTitle)->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->headLink() ?>
        <?= $this->headScript() ?>
    </head>
    <body class="hold-transition sidebar-collapse layout-top-nav <?= $this->getAsset('accentColor') ?>">
        <div class="wrapper">
            <nav class="main-header navbar navbar-expand-md <?= $this->getAsset('topnavbarskin') ?>">
                <div class="container">
                    <a href="<?= $this->url('home') ?>" class="navbar-brand">
                        <img src="<?= $this->basePath($this->getAsset('brandLogo')) ?>" title="<?= $this->getAsset('brandnamefull') ?>" alt="<?= $this->getAsset('brandnamefull') ?>" class="brand-image img-circle elevation-3"
                             style="opacity: .8">
                        <span class="brand-text font-weight-light"><?= $this->getAsset('brandnameshort') ?></span>
                    </a>
                    <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
                        <li class="nav-item">
                            <a class="nav-link sidebar-toggle" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                        </li>
                    </ul>
                    <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse order-3" id="navbarCollapse">
                        <?=
                                $this->navigation('navigation')
                                ->menu($this->getAsset('topNavigationKey'))
                                ->setMinDepth(0)
                                ->setMaxDepth(3)
                                ->setUlClass('navbar-nav')
                                ->setPartial('partial/menu-top')
                        ?>
                        <?= $this->getAsset('showsearch') ? $this->partial('partial/search-form') : '' ?>
                        <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
                            <?= $this->getAsset('showcontrol') ? $this->partial('partial/customize-panel') : '' ?>
                        </ul>
                    </div>
                </div>
            </nav>
            <aside class="main-sidebar sidebar-dark-primary elevation-4">
                <a href="<?= $this->url('home') ?>" class="brand-link <?= $this->getAsset('brandLinkColor') ?>">
                    <img src="<?= $this->basePath($this->getAsset('brandLogo')) ?>" 
                         title="<?= $this->getAsset('brandnamefull') ?>" 
                         alt="<?= $this->getAsset('brandnamefull') ?>" 
                         class="brand-image img-circle elevation-3"
                         style="opacity: .8">
                    <span class="brand-text font-weight-light">
                        <?= $this->getAsset('brandnameshort') ?>
                    </span>
                </a>
                <div class="sidebar">
                    <?= $this->partial(PartialOption::$userInfoSidebar) ?>
                    <nav class="mt-2">
                        <?=
                                $this->navigation('navigation')
                                ->menu($this->getAsset('topNavigationKey'))
                                ->setMinDepth(0)
                                ->setMaxDepth(3)
                                ->setUlClass('nav nav-pills nav-sidebar flex-column')
                                ->setPartial('partial/menu-side')
                        ?>
                    </nav>
                </div>
            </aside>
            <div class="content-wrapper">
                <?php if($this->getAsset('showbreadcrumb')):  ?>
                    <div class="content-header">
                        <div class="container">
                            <div class="row mb-2">
                                <div class="col-sm-6">
                                    <h4 class="m-0" id="pageTitleId">
                                        <?= $this->pageTitle ?>
                                    </h4>
                                </div>
                                <div class="col-sm-6">
                                    <?=
                                    $this->navigation('navigation')
                                        ->breadcrumbs($this->getAsset('navigationKeyForBreadcrumb'))
                                        ->setMinDepth(0)
                                        ->setSeparator('>') 
                                        ->setPartial('partial/breadcrumb')
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="content">
                    <div class="container">
                        <?= $this->content ?>
                    </div>
                </div>
            </div>
            <?= $this->getAsset('showcontrol') ? '<aside class="control-sidebar control-sidebar-dark"></aside>' : '' ?>
            <?= $this->partial('partial/footer') ?>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>

