<?php
$isTopNavigationlayout = $this->getConfig('layout_topnav');
?>
<footer class="main-footer">
    <?= $isTopNavigationlayout == true ? '<div class="container">' : '' ?>
    <div class="float-right d-none d-sm-inline">
        Anything you want
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
    <?= $isTopNavigationlayout == true ? '</div>' : '' ?>
</footer>
