<?php
$isTopNavigationlayout = $this->getConfig('layout_topnav');
?>
<footer class="main-footer">
    <?= $isTopNavigationlayout == true ? '<div class="container">' : '' ?>
    <div class="float-right d-none d-sm-inline">
        
    </div>
    <strong>Copyright &copy; <a href="http://your.company">Your company</a>.</strong> All rights reserved.
    <?= $isTopNavigationlayout == true ? '</div>' : '' ?>
</footer>
