<?php
use LaminasAdminLTE\ThemeOptions\PartialOption;
/**
 * @author Bishwo Prasad Lamichhane <bishwo.prasad@gmail.com>
 */
/* @var $page \Laminas\Navigation\Page\AbstractPage */
$page = $this->page;
$maxDepth = $this->maxDepth;
$class = $this->class;
$linkClass = '';
$labelClean = str_replace(' ', '_', $page->getLabel());
$icon = $page->showIcon == true ? $page->icon : false;
$childPagesCheck = $page->getPages();
foreach ($childPagesCheck as $cPage) {
    if($cPage->isActive()){
        $class .= ' active';
        $linkClass = 'active';
    }
}
?>
<li class="<?= $class ?>">
    <a href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="nav-link dropdown-toggle <?= $linkClass ?>">
        <?= $icon!== false ? '<i class="'. $icon .'"></i>' : '' ?>
        <?= $page->getLabel() ?>
    </a>
    <ul class="dropdown-menu border-0 shadow">
        <?php
        $childPages = $page->getPages();
        foreach ($childPages as $cPage) {
            $iconCpage = $cPage->showIcon == true ? $cPage->icon : false;
            if ($cPage->hasPages() && --$maxDepth > 0) {
                echo $this->partial(PartialOption::$menuItemTree, [
                    'page' => $cPage,
                    'maxDepth' => $maxDepth,
                    'class' => 'dropdown-submenu dropdown-hover'
                ]);
            } else {
                ?>
                <li>
                    <a href="<?= $cPage->getHref() ?>" class="dropdown-item <?= $cPage->isActive()?'active':'' ?>">
                        <?= $iconCpage!== false ? '<i class="'. $iconCpage .'"></i>' : '' ?>
                        <?= $cPage->getLabel() ?>
                    </a>
                </li>
                <?php
            }
        }
        ?>
    </ul>
</li>
