<?php
if ($this->isLoggedIn() == true) {
    $this->userImage = $this->getUserImage();
    $this->userName = $this->getUserName();
    $this->userInfo = $this->getUserInfo();
    ?>
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
            <img src="<?= $this->userImage ?>" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="pull-left info">
            <?= $this->userInfo ?>
        </div>
    </div>
<?php
}