<?php
/**
 * @author Bishwo Prasad Lamichhane <bishwo.prasad@gmail.com>
 */
$this->userImage = "../../dist/img/user2-160x160.jpg";
$this->userInfo = "<a href=\"#\" class=\"d-block\">Alexander Pierce</a>";
?>
<div class="user-panel mt-3 pb-3 mb-3 d-flex">
    <div class="image">
        <img src="<?= $this->userImage ?>" class="img-circle elevation-2" alt="User Image">
    </div>
    <div class="info">
        <?= $this->userInfo ?>
    </div>
</div>
